ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS easiness_factor REAL NOT NULL DEFAULT 2.5;
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS interval_days INTEGER NOT NULL DEFAULT 0;
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS repetitions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS next_review_due TIMESTAMPTZ DEFAULT NULL;
